### ISSUE TITLE
Libsass - last error: unterminated interpolant inside IE function

### ISSUE THREAD

**Issue by mahnunchik** [olivierbossel/gridle#57]
Only one line of code prevents to use gridle with libsass.
```sass
*width: expression((this.parentNode.clientWidth/#{$context}*#{($columns / $name-multiplicator)} - parseInt(this.currentStyle['paddingLeft']) - parseInt(this.currentStyle['paddingRight'])) + 'px');
```
https://github.com/olivierbossel/gridle/blob/master/sass/gridle/_mixins.scss#L243-L245

It will be great if support of IE7 will not interfere to use griddle with fastest sass compiler.

**Comment by olivierbossel** [comment]
Hi mahnunchik,
Thanks for your feedback. I'm currently working on the next release of gridle that will drop support for IE7 so this issue will be corrected at this time.
Thanks again
Cheers!

**Comment by mahnunchik** [comment]
Hi @olivierbossel 

Good news!

Since version [3.2.4](https://github.com/sass/libsass/releases/tag/3.2.4) of libsass gridle no longer affected by this error.
So this issue can be closed. Gridle can be build by [node-sass](https://github.com/sass/node-sass) without any modification.
I've tested:
```bash
$ node-sass -v
node-sass	3.1.0	(Wrapper)	[JavaScript]
libsass  	3.2.4	(Sass Compiler)	[C/C++]
$ node-sass sass/grid.scss css/grid.css
Rendering Complete, saving .css file...
Wrote CSS to /Users/nodejs/gridle/css/grid.css
```

Some ideas about next release:

1. Maybe there is sense to change sass compiler from compass to plain [ruby sass](https://github.com/gruntjs/grunt-contrib-sass)? It is possible because gridle does not use compass features.
1. Another idea is to add some kind of check of ability to build gridle by *fast* sass compiler [node-sass](https://github.com/sass/node-sass). There is [grunt task](https://github.com/sindresorhus/grunt-sass).

**Comment by LukeNZ** [comment]
@mahnunchik  I'm using node-sass 3.1.2 with libsass 3.2.4 and this exact issue is still plaguing me. Any suggestions?

**Comment by veganista** [comment]
One last issue with libsass.... #62
